# Generated by Django 3.1.1 on 2020-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200908_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('out for delivery', 'out for delivery'), ('Delivered', 'delivered')], max_length=200, null=True),
        ),
    ]
